# Change these first
owner: tdeckers-cisco # Your GitHub organization or username, where this repository lives
repo: c2p-upptime # The name of this repository

sites:
  - name: Docs
    url: https://api.ciscoplatform.cloud/docs
  - name: Docs - us-ohaccpb1
    url: https://api.us-ohaccpb1.ciscoplatform.cloud/docs
  - name: Docs - us-oraccpb2
    url: https://api.us-oraccpb2.ciscoplatform.cloud/docs

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /c2p-upptime
  logoUrl: https://raw.githubusercontent.com/tdeckers-cisco/c2p-upptime/master/assets/c2p-transparent.png
  name: Cisco Cloud Platform - Pre-prod
  introTitle: "Cisco Cloud Platform"
  introMessage: C2P Pre-prod status page. No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
